#!/usr/bin/env bash
# Idempotent: Zitadel 에 dev project + OIDC app 등록.
# 첫 부팅 후 1회 실행. 이미 존재하면 skip.
#
# Pre-requisites:
#   docker compose -f infra/zitadel/docker-compose.yml up -d
#   jq must be installed (brew install jq / apt install jq / winget install jqlang.jq)
#
# PAT is auto-generated by Zitadel on first boot via zitadel-setup.yaml
# and written to the zitadel-init-pat Docker volume.
set -euo pipefail

ZITADEL_HOST="${ZITADEL_HOST:-http://localhost:18443}"
COMPOSE_FILE="${COMPOSE_FILE:-$(dirname "$(realpath "$0")")/docker-compose.yml}"
PAT_VOLUME="${PAT_VOLUME:-zitadel_zitadel-init-pat}"

echo "==> Waiting for Zitadel readiness at ${ZITADEL_HOST}/debug/healthz ..."
for i in {1..60}; do
  if curl -sf "${ZITADEL_HOST}/debug/healthz" >/dev/null; then
    echo "    ready."
    break
  fi
  sleep 2
done

echo "==> Reading machine-user PAT from Docker volume (${PAT_VOLUME})"
TOKEN=$(docker run --rm -v "${PAT_VOLUME}:/pat-out" alpine:3.19 \
  sh -c "cat /pat-out/pat 2>/dev/null" 2>/dev/null || true)

if [[ -z "$TOKEN" ]]; then
  echo "ERROR: PAT file not found in volume ${PAT_VOLUME}."
  echo "       Ensure zitadel-setup.yaml is mounted and containers are freshly started."
  echo "       Try: docker compose -f ${COMPOSE_FILE} down -v && docker compose -f ${COMPOSE_FILE} up -d"
  exit 1
fi

echo "==> Create project 'gongzzang-dev'"
PROJECT_RESP=$(curl -sf -X POST "${ZITADEL_HOST}/management/v1/projects" \
  -H "Authorization: Bearer ${TOKEN}" \
  -H "Content-Type: application/json" \
  -d '{"name":"gongzzang-dev"}' 2>&1 || true)
PROJECT_ID=$(echo "$PROJECT_RESP" | jq -r '.id // empty' 2>/dev/null || true)

if [[ -z "$PROJECT_ID" ]]; then
  echo "    project may exist; fetching..."
  PROJECT_ID=$(curl -sf -X POST "${ZITADEL_HOST}/management/v1/projects/_search" \
    -H "Authorization: Bearer ${TOKEN}" \
    -H "Content-Type: application/json" \
    -d '{"queries":[{"nameQuery":{"name":"gongzzang-dev","method":"TEXT_QUERY_METHOD_EQUALS"}}]}' \
    | jq -r '.result[0].id // empty')
fi

echo "    PROJECT_ID=${PROJECT_ID}"

echo "==> Create OIDC app 'gongzzang-web-dev' with PKCE + back-channel logout"
APP_RESP=$(curl -sf -X POST "${ZITADEL_HOST}/management/v1/projects/${PROJECT_ID}/apps/oidc" \
  -H "Authorization: Bearer ${TOKEN}" \
  -H "Content-Type: application/json" \
  -d '{
    "name": "gongzzang-web-dev",
    "redirectUris": ["http://localhost:3000/api/auth/callback"],
    "postLogoutRedirectUris": ["http://localhost:3000/"],
    "responseTypes": ["OIDC_RESPONSE_TYPE_CODE"],
    "grantTypes": ["OIDC_GRANT_TYPE_AUTHORIZATION_CODE","OIDC_GRANT_TYPE_REFRESH_TOKEN"],
    "appType": "OIDC_APP_TYPE_WEB",
    "authMethodType": "OIDC_AUTH_METHOD_TYPE_NONE",
    "version": "OIDC_VERSION_1_0",
    "devMode": true,
    "accessTokenType": "OIDC_TOKEN_TYPE_JWT",
    "idTokenRoleAssertion": true,
    "accessTokenRoleAssertion": true,
    "skipNativeAppSuccessPage": true
  }')

CLIENT_ID=$(echo "$APP_RESP" | jq -r '.clientId // empty')
echo "    CLIENT_ID=${CLIENT_ID}"

cat <<EOF

================================================================
Zitadel dev setup complete.

Add to apps/web/.env.local:
  ZITADEL_CLIENT_ID=${CLIENT_ID}
  ZITADEL_AUDIENCE=${CLIENT_ID}

Verify: open http://localhost:18443/ui/console (admin / Admin123!)
================================================================
EOF
