//! Generated traffic/auth serving policy from docs/architecture/traffic-auth-policy-registry.v1.json.
//! Run scripts/ci/generate-traffic-auth-policy.ps1 after editing the registry.

use crate::backend_authorization::BackendRolePolicy;
use crate::backend_rate_limit::{BackendRateKeyStrategy, BackendRatePolicy};
use user_domain::entity::UserRole;

pub const BACKEND_RATE_POLICIES: &[BackendRatePolicy] = &[
    BackendRatePolicy {
        method: "GET",
        path_pattern: "/map/v1/marker-tiles/listing/:z/:x/:y.pbf",
        key_prefix: "public-map:listing-marker-tile",
        key_strategy: BackendRateKeyStrategy::ClientIp,
        limit: 600,
        window_seconds: 60,
        problem_type: "map/too-many-public-marker-requests",
    },
    BackendRatePolicy {
        method: "GET",
        path_pattern: "/map/v1/marker-counts/listing",
        key_prefix: "public-map:listing-marker-count",
        key_strategy: BackendRateKeyStrategy::ClientIp,
        limit: 120,
        window_seconds: 60,
        problem_type: "map/too-many-public-marker-requests",
    },
    BackendRatePolicy {
        method: "POST",
        path_pattern: "/map/v1/marker-filters/listing",
        key_prefix: "public-map:listing-marker-filter",
        key_strategy: BackendRateKeyStrategy::ClientIp,
        limit: 60,
        window_seconds: 60,
        problem_type: "map/too-many-public-marker-requests",
    },
    BackendRatePolicy {
        method: "GET",
        path_pattern: "/map/v1/marker-masks/listing/:z/:x/:y",
        key_prefix: "public-map:listing-marker-mask",
        key_strategy: BackendRateKeyStrategy::ClientIp,
        limit: 120,
        window_seconds: 60,
        problem_type: "map/too-many-public-marker-requests",
    },
    BackendRatePolicy {
        method: "GET",
        path_pattern: "/map/v1/marker-tombstones/listing/:z/:x/:y",
        key_prefix: "public-map:listing-marker-tombstone",
        key_strategy: BackendRateKeyStrategy::ClientIp,
        limit: 120,
        window_seconds: 60,
        problem_type: "map/too-many-public-marker-requests",
    },
    BackendRatePolicy {
        method: "GET",
        path_pattern: "/map/v1/marker-deltas/listing/:z/:x/:y.pbf",
        key_prefix: "public-map:listing-marker-delta",
        key_strategy: BackendRateKeyStrategy::ClientIp,
        limit: 120,
        window_seconds: 60,
        problem_type: "map/too-many-public-marker-requests",
    },
    BackendRatePolicy {
        method: "GET",
        path_pattern: "/users/me",
        key_prefix: "api-proxy:authenticated-read",
        key_strategy: BackendRateKeyStrategy::SessionSub,
        limit: 240,
        window_seconds: 60,
        problem_type: "proxy/too-many-requests",
    },
    BackendRatePolicy {
        method: "GET",
        path_pattern: "/users/:id",
        key_prefix: "api-proxy:authenticated-read",
        key_strategy: BackendRateKeyStrategy::SessionSub,
        limit: 240,
        window_seconds: 60,
        problem_type: "proxy/too-many-requests",
    },
    BackendRatePolicy {
        method: "GET",
        path_pattern: "/listings",
        key_prefix: "api-proxy:authenticated-read",
        key_strategy: BackendRateKeyStrategy::SessionSub,
        limit: 240,
        window_seconds: 60,
        problem_type: "proxy/too-many-requests",
    },
    BackendRatePolicy {
        method: "POST",
        path_pattern: "/listings",
        key_prefix: "api-proxy:privileged-write",
        key_strategy: BackendRateKeyStrategy::SessionSub,
        limit: 60,
        window_seconds: 60,
        problem_type: "proxy/too-many-requests",
    },
    BackendRatePolicy {
        method: "GET",
        path_pattern: "/listings/:id",
        key_prefix: "api-proxy:authenticated-read",
        key_strategy: BackendRateKeyStrategy::SessionSub,
        limit: 240,
        window_seconds: 60,
        problem_type: "proxy/too-many-requests",
    },
    BackendRatePolicy {
        method: "PATCH",
        path_pattern: "/listings/:id",
        key_prefix: "api-proxy:privileged-write",
        key_strategy: BackendRateKeyStrategy::SessionSub,
        limit: 60,
        window_seconds: 60,
        problem_type: "proxy/too-many-requests",
    },
    BackendRatePolicy {
        method: "POST",
        path_pattern: "/listings/:id/submit-for-review",
        key_prefix: "api-proxy:privileged-write",
        key_strategy: BackendRateKeyStrategy::SessionSub,
        limit: 60,
        window_seconds: 60,
        problem_type: "proxy/too-many-requests",
    },
    BackendRatePolicy {
        method: "POST",
        path_pattern: "/listings/:id/revise",
        key_prefix: "api-proxy:privileged-write",
        key_strategy: BackendRateKeyStrategy::SessionSub,
        limit: 60,
        window_seconds: 60,
        problem_type: "proxy/too-many-requests",
    },
    BackendRatePolicy {
        method: "POST",
        path_pattern: "/listings/:id/photos",
        key_prefix: "api-proxy:privileged-write",
        key_strategy: BackendRateKeyStrategy::SessionSub,
        limit: 60,
        window_seconds: 60,
        problem_type: "proxy/too-many-requests",
    },
    BackendRatePolicy {
        method: "GET",
        path_pattern: "/listings/:listing_id/photos/:photo_id",
        key_prefix: "api-proxy:authenticated-read",
        key_strategy: BackendRateKeyStrategy::SessionSub,
        limit: 240,
        window_seconds: 60,
        problem_type: "proxy/too-many-requests",
    },
    BackendRatePolicy {
        method: "DELETE",
        path_pattern: "/listings/:listing_id/photos/:photo_id",
        key_prefix: "api-proxy:privileged-write",
        key_strategy: BackendRateKeyStrategy::SessionSub,
        limit: 60,
        window_seconds: 60,
        problem_type: "proxy/too-many-requests",
    },
    BackendRatePolicy {
        method: "POST",
        path_pattern: "/listings/:listing_id/photos/:photo_id/confirm",
        key_prefix: "api-proxy:privileged-write",
        key_strategy: BackendRateKeyStrategy::SessionSub,
        limit: 60,
        window_seconds: 60,
        problem_type: "proxy/too-many-requests",
    },
    BackendRatePolicy {
        method: "POST",
        path_pattern: "/listings/:id/bookmark",
        key_prefix: "api-proxy:authenticated-write",
        key_strategy: BackendRateKeyStrategy::SessionSub,
        limit: 120,
        window_seconds: 60,
        problem_type: "proxy/too-many-requests",
    },
    BackendRatePolicy {
        method: "DELETE",
        path_pattern: "/listings/:id/bookmark",
        key_prefix: "api-proxy:authenticated-write",
        key_strategy: BackendRateKeyStrategy::SessionSub,
        limit: 120,
        window_seconds: 60,
        problem_type: "proxy/too-many-requests",
    },
    BackendRatePolicy {
        method: "GET",
        path_pattern: "/me/bookmarks",
        key_prefix: "api-proxy:authenticated-read",
        key_strategy: BackendRateKeyStrategy::SessionSub,
        limit: 240,
        window_seconds: 60,
        problem_type: "proxy/too-many-requests",
    },
    BackendRatePolicy {
        method: "GET",
        path_pattern: "/api/parcels/:pnu",
        key_prefix: "api-proxy:authenticated-read",
        key_strategy: BackendRateKeyStrategy::SessionSub,
        limit: 240,
        window_seconds: 60,
        problem_type: "proxy/too-many-requests",
    },
    BackendRatePolicy {
        method: "GET",
        path_pattern: "/api/buildings",
        key_prefix: "api-proxy:authenticated-read",
        key_strategy: BackendRateKeyStrategy::SessionSub,
        limit: 240,
        window_seconds: 60,
        problem_type: "proxy/too-many-requests",
    },
    BackendRatePolicy {
        method: "POST",
        path_pattern: "/admin/listings/:id/approve",
        key_prefix: "api-proxy:privileged-write",
        key_strategy: BackendRateKeyStrategy::SessionSub,
        limit: 60,
        window_seconds: 60,
        problem_type: "proxy/too-many-requests",
    },
    BackendRatePolicy {
        method: "POST",
        path_pattern: "/admin/listings/:id/reject",
        key_prefix: "api-proxy:privileged-write",
        key_strategy: BackendRateKeyStrategy::SessionSub,
        limit: 60,
        window_seconds: 60,
        problem_type: "proxy/too-many-requests",
    },
    BackendRatePolicy {
        method: "GET",
        path_pattern: "/me/notifications",
        key_prefix: "api-proxy:authenticated-read",
        key_strategy: BackendRateKeyStrategy::SessionSub,
        limit: 240,
        window_seconds: 60,
        problem_type: "proxy/too-many-requests",
    },
    BackendRatePolicy {
        method: "GET",
        path_pattern: "/me/notifications/unread-count",
        key_prefix: "api-proxy:authenticated-read",
        key_strategy: BackendRateKeyStrategy::SessionSub,
        limit: 240,
        window_seconds: 60,
        problem_type: "proxy/too-many-requests",
    },
    BackendRatePolicy {
        method: "PATCH",
        path_pattern: "/me/notifications/:id/read",
        key_prefix: "api-proxy:authenticated-write",
        key_strategy: BackendRateKeyStrategy::SessionSub,
        limit: 120,
        window_seconds: 60,
        problem_type: "proxy/too-many-requests",
    },
    BackendRatePolicy {
        method: "POST",
        path_pattern: "/me/notifications/mark-all-read",
        key_prefix: "api-proxy:authenticated-write",
        key_strategy: BackendRateKeyStrategy::SessionSub,
        limit: 120,
        window_seconds: 60,
        problem_type: "proxy/too-many-requests",
    },
];

pub const BACKEND_ROLE_POLICIES: &[BackendRolePolicy] = &[
    BackendRolePolicy {
        method: "POST",
        path_pattern: "/listings",
        required_roles: &[UserRole::Broker],
    },
    BackendRolePolicy {
        method: "PATCH",
        path_pattern: "/listings/:id",
        required_roles: &[UserRole::Broker],
    },
    BackendRolePolicy {
        method: "POST",
        path_pattern: "/listings/:id/submit-for-review",
        required_roles: &[UserRole::Broker],
    },
    BackendRolePolicy {
        method: "POST",
        path_pattern: "/listings/:id/revise",
        required_roles: &[UserRole::Broker],
    },
    BackendRolePolicy {
        method: "POST",
        path_pattern: "/listings/:id/photos",
        required_roles: &[UserRole::Broker],
    },
    BackendRolePolicy {
        method: "DELETE",
        path_pattern: "/listings/:listing_id/photos/:photo_id",
        required_roles: &[UserRole::Broker],
    },
    BackendRolePolicy {
        method: "POST",
        path_pattern: "/listings/:listing_id/photos/:photo_id/confirm",
        required_roles: &[UserRole::Broker],
    },
    BackendRolePolicy {
        method: "POST",
        path_pattern: "/admin/listings/:id/approve",
        required_roles: &[UserRole::Admin, UserRole::Operator],
    },
    BackendRolePolicy {
        method: "POST",
        path_pattern: "/admin/listings/:id/reject",
        required_roles: &[UserRole::Admin, UserRole::Operator],
    },
];
